application:
  actions: actions
  runtimeManifest:
    packages:
      block-party-demo:
        actions:
          newsletter:
            function: actions/handle-submit/index.js
            web: 'yes'
            runtime: 'nodejs:14'
            inputs:
              LOG_LEVEL: debug
              CAPTCHA_SITE_KEY: $CAPTCHA_SITE_KEY
              CAPTCHA_SECRET_KEY: $CAPTCHA_SECRET_KEY
            annotations:
              require-adobe-auth: false
              final: true
